export default [
  "Turkmenistan",
  "Saudi Arabia",
  "Fr. Polynesia",
  "Suriname",
  "El Salvador",
  "Benin",
  "Jersey",
  "Egypt",
  "Israel",
  "Malta",
  "Micronesia",
  "Bolivia",
  "Yemen",
  "Monaco",
  "Brazil",
  "Turks and Caicos Is.",
  "Samoa",
  "Palau",
  "São Tomé and Principe",
  "Argentina",
  "Germany",
  "South Africa",
  "Lebanon",
  "Dominica",
  "Marshall Is.",
  "Gambia",
  "Uzbekistan",
  "Austria",
  "Finland",
  "Tunisia",
  "Ukraine",
  "Croatia",
  "Luxembourg",
  "American Samoa",
  "Norway",
  "Burundi",
  "Macedonia",
  "Andorra",
  "Philippines",
  "Niger",
  "South Korea",
  "N. Cyprus",
  "Cameroon",
  "Sweden",
  "Angola",
  "Ecuador",
  "Tajikistan",
  "San Marino",
  "Guernsey",
  "Italy",
  "Kenya",
  "Paraguay",
  "Bulgaria",
  "Curaçao",
  "Belgium",
  "Antigua and Barb.",
  "Laos",
  "Kosovo",
  "China",
  "Bahrain",
  "Br. Indian Ocean Ter.",
  "Bahamas",
  "Portugal",
  "Congo",
  "Guinea",
  "Eritrea",
  "Vatican",
  "Hungary",
  "Coral Sea Is.",
  "Oman",
  "Guinea-Bissau",
  "S. Geo. and the Is.",
  "Iran",
  "eSwatini",
  "Djibouti",
  "Sierra Leone",
  "Bhutan",
  "Palestine",
  "St-Martin",
  "Antarctica",
  "Scarborough Reef",
  "Côte d'Ivoire",
  "Jordan",
  "Bajo Nuevo Bank",
  "New Caledonia",
  "Guam",
  "United Kingdom",
  "Kazakhstan",
  "Sri Lanka",
  "Algeria",
  "Gibraltar",
  "Venezuela",
  "Gabon",
  "Poland",
  "Mexico",
  "Somaliland",
  "Albania",
  "Zimbabwe",
  "Denmark",
  "Japan",
  "St. Vin. and Gren.",
  "Cyprus",
  "St-Barthélemy",
  "France",
  "Mali",
  "Eq. Guinea",
  "Burkina Faso",
  "Somalia",
  "Jamaica",
  "Rwanda",
  "Uruguay",
  "Haiti",
  "Tonga",
  "W. Sahara",
  "Cyprus U.N. Buffer Zone",
  "Romania",
  "Greece",
  "Brunei",
  "Peru",
  "St. Pierre and Miquelon",
  "Åland",
  "Spain",
  "Bangladesh",
  "Serbia",
  "Moldova",
  "Lithuania",
  "Syria",
  "Botswana",
  "Fr. S. Antarctic Lands",
  "Dominican Rep.",
  "Hong Kong",
  "Nepal",
  "Nigeria",
  "Grenada",
  "Liechtenstein",
  "Maldives",
  "Indonesia",
  "Serranilla Bank",
  "Indian Ocean Ter.",
  "Pakistan",
  "Lesotho",
  "Ethiopia",
  "Panama",
  "Bermuda",
  "Mongolia",
  "Sint Maarten",
  "Slovakia",
  "Tanzania",
  "North Korea",
  "Senegal",
  "Armenia",
  "Canada",
  "Estonia",
  "Aruba",
  "Chad",
  "Singapore",
  "Bosnia and Herz.",
  "Wallis and Futuna Is.",
  "New Zealand",
  "Central African Rep.",
  "Uganda",
  "Thailand",
  "Comoros",
  "Faeroe Is.",
  "Sudan",
  "Puerto Rico",
  "Malaysia",
  "Trinidad and Tobago",
  "Solomon Is.",
  "Latvia",
  "India",
  "Cuba",
  "Siachen Glacier",
  "Chile",
  "Clipperton I.",
  "Morocco",
  "Afghanistan",
  "Ireland",
  "Macao",
  "Niue",
  "Switzerland",
  "Tuvalu",
  "Myanmar",
  "USNB Guantanamo Bay",
  "Guyana",
  "Dem. Rep. Congo",
  "Heard I. and McDonald Is.",
  "Guatemala",
  "Costa Rica",
  "Montserrat",
  "Baikonur",
  "Namibia",
  "Liberia",
  "Iraq",
  "Mauritania",
  "Turkey",
  "U.S. Virgin Is.",
  "U.S. Minor Outlying Is.",
  "Saint Lucia",
  "St. Kitts and Nevis",
  "Vietnam",
  "Cabo Verde",
  "Mozambique",
  "Cambodia",
  "Kuwait",
  "British Virgin Is.",
  "Pitcairn Is.",
  "Qatar",
  "United States of America",
  "Isle of Man",
  "Akrotiri",
  "Greenland",
  "Ashmore and Cartier Is.",
  "Kyrgyzstan",
  "Libya",
  "Falkland Is.",
  "Georgia",
  "S. Sudan",
  "Cook Is.",
  "United Arab Emirates",
  "Belarus",
  "Russia",
  "Slovenia",
  "Colombia",
  "Saint Helena",
  "Czechia",
  "Zambia",
  "Madagascar",
  "N. Mariana Is.",
  "Spratly Is.",
  "Timor-Leste",
  "Azerbaijan",
  "Nauru",
  "Malawi",
  "Iceland",
  "Honduras",
  "Togo",
  "Norfolk Island",
  "Seychelles",
  "Nicaragua",
  "Fiji",
  "Belize",
  "Taiwan",
  "Papua New Guinea",
  "Mauritius",
  "Ghana",
  "Dhekelia",
  "Vanuatu",
  "Cayman Is.",
  "Australia",
  "Barbados",
  "Kiribati",
  "Montenegro",
  "Netherlands",
  "Anguilla",
];
